package fr.ttfx.cow4.world;

import com.google.gson.JsonObject;

/**
 * Created by Arsenik on 18/08/15.
 */

/**
 * Contains all informations about the game.
 * This class is
 */
public class StaticGameWorld extends GameWorld {
        public StaticGameWorld() {
                labyrinth = new Cell[][]{
                        {
                                new Cell(false, true, false, true, 0, 0),
                                new Cell(true, true, false, false, 0, 1),
                                new Cell(true, true, false, false, 0, 2),
                                new Cell(true, true, false, false, 0, 3),
                                new Cell(true, true, false, false, 0, 4),
                                new Cell(true, true, false, false, 0, 5),
                                new Cell(true, true, false, false, 0, 6),
                                new Cell(true, true, false, true, 0, 7),
                                new Cell(true, true, false, false, 0, 8),
                                new Cell(true, true, false, false, 0, 9),
                                new Cell(true, true, false, true, 0, 10),
                                new Cell(true, true, false, false, 0, 11),
                                new Cell(true, true, false, false, 0, 12),
                                new Cell(true, false, false, true, 0, 13),
                                new Cell(false, false, false, false, 0, 14),
                                new Cell(false, true, false, true, 0, 15),
                                new Cell(true, true, false, false, 0, 16),
                                new Cell(true, true, false, false, 0, 17),
                                new Cell(true, true, false, false, 0, 18),
                                new Cell(true, true, false, false, 0, 19),
                                new Cell(true, true, false, false, 0, 20),
                                new Cell(true, true, false, false, 0, 21),
                                new Cell(true, true, false, false, 0, 22),
                                new Cell(true, true, false, false, 0, 23),
                                new Cell(true, false, false, true, 0, 24)
                        },
                        {
                                new Cell(false, false, true, true, 1, 0),
                                new Cell(false, true, false, true, 1, 1),
                                new Cell(true, true, false, false, 1, 2),
                                new Cell(true, false, false, true, 1, 3),
                                new Cell(false, true, false, true, 1, 4),
                                new Cell(true, true, false, false, 1, 5),
                                new Cell(true, false, false, true, 1, 6),
                                new Cell(false, true, true, false, 1, 7),
                                new Cell(true, true, false, false, 1, 8),
                                new Cell(true, false, false, true, 1, 9),
                                new Cell(false, true, true, false, 1, 10),
                                new Cell(true, true, false, false, 1, 11),
                                new Cell(true, false, false, true, 1, 12),
                                new Cell(false, true, true, false, 1, 13),
                                new Cell(true, true, false, false, 1, 14),
                                new Cell(true, false, true, false, 1, 15),
                                new Cell(false, true, false, true, 1, 16),
                                new Cell(true, true, false, false, 1, 17),
                                new Cell(true, true, false, false, 1, 18),
                                new Cell(true, true, false, false, 1, 19),
                                new Cell(true, true, false, false, 1, 20),
                                new Cell(true, true, false, false, 1, 21),
                                new Cell(true, true, false, false, 1, 22),
                                new Cell(true, true, false, false, 1, 23),
                                new Cell(true, false, true, false, 1, 24)
                        },
                        {
                                new Cell(false, true, true, false, 2, 0),
                                new Cell(true, false, true, false, 2, 1),
                                new Cell(false, true, false, false, 2, 2),
                                new Cell(true, true, true, false, 2, 3),
                                new Cell(true, false, true, false, 2, 4),
                                new Cell(false, true, false, true, 2, 5),
                                new Cell(true, true, true, false, 2, 6),
                                new Cell(true, true, false, false, 2, 7),
                                new Cell(true, false, false, true, 2, 8),
                                new Cell(false, true, true, false, 2, 9),
                                new Cell(true, true, false, false, 2, 10),
                                new Cell(true, false, false, true, 2, 11),
                                new Cell(false, true, true, false, 2, 12),
                                new Cell(true, true, false, false, 2, 13),
                                new Cell(true, true, false, false, 2, 14),
                                new Cell(true, true, false, false, 2, 15),
                                new Cell(true, false, true, true, 2, 16),
                                new Cell(false, true, false, true, 2, 17),
                                new Cell(true, true, false, false, 2, 18),
                                new Cell(true, true, false, false, 2, 19),
                                new Cell(true, true, false, false, 2, 20),
                                new Cell(true, true, false, false, 2, 21),
                                new Cell(true, true, false, false, 2, 22),
                                new Cell(true, true, false, false, 2, 23),
                                new Cell(true, false, false, true, 2, 24)
                        },
                        {
                                new Cell(false, true, false, true, 3, 0),
                                new Cell(true, true, false, false, 3, 1),
                                new Cell(true, true, false, false, 3, 2),
                                new Cell(true, true, false, false, 3, 3),
                                new Cell(true, true, false, false, 3, 4),
                                new Cell(true, false, true, true, 3, 5),
                                new Cell(false, true, false, true, 3, 6),
                                new Cell(true, false, false, true, 3, 7),
                                new Cell(false, true, true, false, 3, 8),
                                new Cell(true, true, false, false, 3, 9),
                                new Cell(true, false, false, true, 3, 10),
                                new Cell(false, true, true, false, 3, 11),
                                new Cell(true, true, false, false, 3, 12),
                                new Cell(true, true, false, false, 3, 13),
                                new Cell(true, true, false, false, 3, 14),
                                new Cell(true, false, false, true, 3, 15),
                                new Cell(false, true, true, false, 3, 16),
                                new Cell(true, false, true, false, 3, 17),
                                new Cell(false, true, false, true, 3, 18),
                                new Cell(true, true, false, false, 3, 19),
                                new Cell(true, true, false, true, 3, 20),
                                new Cell(true, true, false, false, 3, 21),
                                new Cell(true, true, false, false, 3, 22),
                                new Cell(true, true, false, false, 3, 23),
                                new Cell(true, false, true, false, 3, 24)
                        },
                        {
                                new Cell(false, false, true, true, 4, 0),
                                new Cell(false, true, false, true, 4, 1),
                                new Cell(true, true, false, false, 4, 2),
                                new Cell(true, true, false, false, 4, 3),
                                new Cell(true, true, false, false, 4, 4),
                                new Cell(true, false, true, false, 4, 5),
                                new Cell(false, false, true, true, 4, 6),
                                new Cell(false, false, true, true, 4, 7),
                                new Cell(false, true, false, false, 4, 8),
                                new Cell(true, true, false, false, 4, 9),
                                new Cell(true, true, true, false, 4, 10),
                                new Cell(true, true, false, false, 4, 11),
                                new Cell(true, true, false, false, 4, 12),
                                new Cell(true, true, false, true, 4, 13),
                                new Cell(true, true, false, false, 4, 14),
                                new Cell(true, true, true, false, 4, 15),
                                new Cell(true, true, false, false, 4, 16),
                                new Cell(true, true, false, false, 4, 17),
                                new Cell(true, true, true, true, 4, 18),
                                new Cell(true, true, false, false, 4, 19),
                                new Cell(true, false, true, true, 4, 20),
                                new Cell(false, true, false, false, 4, 21),
                                new Cell(true, true, false, false, 4, 22),
                                new Cell(true, true, false, false, 4, 23),
                                new Cell(true, false, false, true, 4, 24)
                        },
                        {
                                new Cell(false, false, true, true, 5, 0),
                                new Cell(false, false, true, true, 5, 1),
                                new Cell(false, true, false, true, 5, 2),
                                new Cell(true, true, false, false, 5, 3),
                                new Cell(true, true, false, false, 5, 4),
                                new Cell(true, true, false, false, 5, 5),
                                new Cell(true, false, true, false, 5, 6),
                                new Cell(false, true, true, false, 5, 7),
                                new Cell(true, true, false, false, 5, 8),
                                new Cell(true, true, false, false, 5, 9),
                                new Cell(true, false, false, true, 5, 10),
                                new Cell(false, true, false, true, 5, 11),
                                new Cell(true, false, false, true, 5, 12),
                                new Cell(false, true, true, false, 5, 13),
                                new Cell(true, true, false, false, 5, 14),
                                new Cell(true, true, false, false, 5, 15),
                                new Cell(true, true, false, false, 5, 16),
                                new Cell(true, true, false, false, 5, 17),
                                new Cell(true, true, true, true, 5, 18),
                                new Cell(true, true, false, false, 5, 19),
                                new Cell(true, true, true, false, 5, 20),
                                new Cell(true, true, false, false, 5, 21),
                                new Cell(true, true, false, false, 5, 22),
                                new Cell(true, true, false, false, 5, 23),
                                new Cell(true, false, true, false, 5, 24)
                        },
                        {
                                new Cell(false, false, true, true, 6, 0),
                                new Cell(false, false, true, true, 6, 1),
                                new Cell(false, true, true, false, 6, 2),
                                new Cell(true, true, false, false, 6, 3),
                                new Cell(true, true, false, false, 6, 4),
                                new Cell(true, false, false, true, 6, 5),
                                new Cell(false, true, false, true, 6, 6),
                                new Cell(true, true, false, false, 6, 7),
                                new Cell(true, true, false, false, 6, 8),
                                new Cell(true, false, false, true, 6, 9),
                                new Cell(false, false, true, true, 6, 10),
                                new Cell(false, false, true, true, 6, 11),
                                new Cell(false, true, true, false, 6, 12),
                                new Cell(true, true, false, false, 6, 13),
                                new Cell(true, true, false, false, 6, 14),
                                new Cell(true, true, false, false, 6, 15),
                                new Cell(true, true, false, false, 6, 16),
                                new Cell(true, false, false, true, 6, 17),
                                new Cell(false, true, true, false, 6, 18),
                                new Cell(true, true, false, false, 6, 19),
                                new Cell(true, true, false, false, 6, 20),
                                new Cell(true, true, false, false, 6, 21),
                                new Cell(true, true, false, false, 6, 22),
                                new Cell(true, true, false, false, 6, 23),
                                new Cell(true, false, false, true, 6, 24)
                        },
                        {
                                new Cell(false, false, true, true, 7, 0),
                                new Cell(false, true, true, false, 7, 1),
                                new Cell(true, true, false, false, 7, 2),
                                new Cell(true, true, false, false, 7, 3),
                                new Cell(true, true, false, false, 7, 4),
                                new Cell(true, false, true, false, 7, 5),
                                new Cell(false, true, true, false, 7, 6),
                                new Cell(true, true, false, false, 7, 7),
                                new Cell(true, false, false, true, 7, 8),
                                new Cell(false, true, true, false, 7, 9),
                                new Cell(true, false, true, false, 7, 10),
                                new Cell(false, true, true, false, 7, 11),
                                new Cell(true, true, false, false, 7, 12),
                                new Cell(true, true, false, false, 7, 13),
                                new Cell(true, true, false, false, 7, 14),
                                new Cell(true, true, false, false, 7, 15),
                                new Cell(true, false, false, true, 7, 16),
                                new Cell(false, true, true, true, 7, 17),
                                new Cell(true, false, false, true, 7, 18),
                                new Cell(false, true, false, true, 7, 19),
                                new Cell(true, true, false, true, 7, 20),
                                new Cell(true, true, false, false, 7, 21),
                                new Cell(true, true, false, false, 7, 22),
                                new Cell(true, true, false, false, 7, 23),
                                new Cell(true, false, true, true, 7, 24)
                        },
                        {
                                new Cell(false, true, true, false, 8, 0),
                                new Cell(true, true, false, false, 8, 1),
                                new Cell(true, true, false, false, 8, 2),
                                new Cell(true, true, false, true, 8, 3),
                                new Cell(true, true, false, false, 8, 4),
                                new Cell(true, true, false, false, 8, 5),
                                new Cell(true, true, false, false, 8, 6),
                                new Cell(true, false, false, false, 8, 7),
                                new Cell(false, true, true, false, 8, 8),
                                new Cell(true, true, false, false, 8, 9),
                                new Cell(true, true, false, false, 8, 10),
                                new Cell(true, true, false, false, 8, 11),
                                new Cell(true, true, false, true, 8, 12),
                                new Cell(true, true, false, false, 8, 13),
                                new Cell(true, true, false, false, 8, 14),
                                new Cell(true, true, false, false, 8, 15),
                                new Cell(true, false, true, false, 8, 16),
                                new Cell(false, false, true, false, 8, 17),
                                new Cell(false, true, true, false, 8, 18),
                                new Cell(true, false, true, false, 8, 19),
                                new Cell(false, false, true, true, 8, 20),
                                new Cell(false, true, false, false, 8, 21),
                                new Cell(true, true, false, false, 8, 22),
                                new Cell(true, true, false, false, 8, 23),
                                new Cell(true, false, true, false, 8, 24)
                        },
                        {
                                new Cell(false, true, false, true, 9, 0),
                                new Cell(true, true, false, false, 9, 1),
                                new Cell(true, true, false, false, 9, 2),
                                new Cell(true, true, true, false, 9, 3),
                                new Cell(true, true, false, false, 9, 4),
                                new Cell(true, true, false, false, 9, 5),
                                new Cell(true, true, false, false, 9, 6),
                                new Cell(true, false, false, false, 9, 7),
                                new Cell(false, true, false, true, 9, 8),
                                new Cell(true, true, false, false, 9, 9),
                                new Cell(true, true, false, false, 9, 10),
                                new Cell(true, true, false, false, 9, 11),
                                new Cell(true, true, true, false, 9, 12),
                                new Cell(true, true, false, false, 9, 13),
                                new Cell(true, true, false, false, 9, 14),
                                new Cell(true, true, false, false, 9, 15),
                                new Cell(true, false, false, false, 9, 16),
                                new Cell(false, true, false, true, 9, 17),
                                new Cell(true, true, false, false, 9, 18),
                                new Cell(true, true, false, false, 9, 19),
                                new Cell(true, true, true, false, 9, 20),
                                new Cell(true, true, false, false, 9, 21),
                                new Cell(true, true, false, false, 9, 22),
                                new Cell(true, true, false, false, 9, 23),
                                new Cell(true, false, false, true, 9, 24)
                        },
                        {
                                new Cell(false, true, true, false, 10, 0),
                                new Cell(true, true, false, false, 10, 1),
                                new Cell(true, true, false, false, 10, 2),
                                new Cell(true, true, false, false, 10, 3),
                                new Cell(true, true, false, true, 10, 4),
                                new Cell(true, true, false, true, 10, 5),
                                new Cell(true, true, false, false, 10, 6),
                                new Cell(true, false, false, false, 10, 7),
                                new Cell(false, true, true, true, 10, 8),
                                new Cell(true, true, false, false, 10, 9),
                                new Cell(true, true, false, false, 10, 10),
                                new Cell(true, true, false, false, 10, 11),
                                new Cell(true, true, false, true, 10, 12),
                                new Cell(true, true, false, false, 10, 13),
                                new Cell(true, true, false, false, 10, 14),
                                new Cell(true, true, false, false, 10, 15),
                                new Cell(true, false, false, true, 10, 16),
                                new Cell(false, true, true, false, 10, 17),
                                new Cell(true, true, false, false, 10, 18),
                                new Cell(true, true, false, false, 10, 19),
                                new Cell(true, true, false, true, 10, 20),
                                new Cell(true, true, false, true, 10, 21),
                                new Cell(true, true, false, false, 10, 22),
                                new Cell(true, true, false, false, 10, 23),
                                new Cell(true, false, true, false, 10, 24)
                        },
                        {
                                new Cell(false, true, false, true, 11, 0),
                                new Cell(true, true, false, false, 11, 1),
                                new Cell(true, true, false, false, 11, 2),
                                new Cell(true, true, false, false, 11, 3),
                                new Cell(true, false, true, false, 11, 4),
                                new Cell(false, true, true, false, 11, 5),
                                new Cell(true, true, false, false, 11, 6),
                                new Cell(true, true, false, false, 11, 7),
                                new Cell(true, true, true, false, 11, 8),
                                new Cell(true, true, false, false, 11, 9),
                                new Cell(true, false, false, false, 11, 10),
                                new Cell(false, true, false, true, 11, 11),
                                new Cell(true, true, true, false, 11, 12),
                                new Cell(true, false, false, true, 11, 13),
                                new Cell(false, true, false, false, 11, 14),
                                new Cell(true, true, false, false, 11, 15),
                                new Cell(true, true, true, false, 11, 16),
                                new Cell(true, true, false, false, 11, 17),
                                new Cell(true, true, false, false, 11, 18),
                                new Cell(true, true, false, false, 11, 19),
                                new Cell(true, false, true, false, 11, 20),
                                new Cell(false, true, true, false, 11, 21),
                                new Cell(true, true, false, false, 11, 22),
                                new Cell(true, true, false, false, 11, 23),
                                new Cell(true, false, false, true, 11, 24)
                        },
                        {
                                new Cell(false, true, true, true, 12, 0),
                                new Cell(true, true, false, false, 12, 1),
                                new Cell(true, true, false, false, 12, 2),
                                new Cell(true, true, false, false, 12, 3),
                                new Cell(true, true, false, false, 12, 4),
                                new Cell(true, true, false, false, 12, 5),
                                new Cell(true, true, false, false, 12, 6),
                                new Cell(true, true, false, false, 12, 7),
                                new Cell(true, true, false, false, 12, 8),
                                new Cell(true, true, false, false, 12, 9),
                                new Cell(true, true, false, false, 12, 10),
                                new Cell(true, true, true, true, 12, 11),
                                new Cell(true, true, false, false, 12, 12),
                                new Cell(true, true, true, true, 12, 13),
                                new Cell(true, true, false, false, 12, 14),
                                new Cell(true, true, false, false, 12, 15),
                                new Cell(true, true, false, false, 12, 16),
                                new Cell(true, true, false, false, 12, 17),
                                new Cell(true, true, false, false, 12, 18),
                                new Cell(true, true, false, false, 12, 19),
                                new Cell(true, true, false, false, 12, 20),
                                new Cell(true, true, false, false, 12, 21),
                                new Cell(true, true, false, false, 12, 22),
                                new Cell(true, true, false, false, 12, 23),
                                new Cell(true, false, true, true, 12, 24)
                        },
                        {
                                new Cell(false, true, true, false, 13, 0),
                                new Cell(true, true, false, false, 13, 1),
                                new Cell(true, true, false, false, 13, 2),
                                new Cell(true, false, false, true, 13, 3),
                                new Cell(false, true, false, true, 13, 4),
                                new Cell(true, true, false, false, 13, 5),
                                new Cell(true, true, false, false, 13, 6),
                                new Cell(true, true, false, false, 13, 7),
                                new Cell(true, true, false, true, 13, 8),
                                new Cell(true, true, false, false, 13, 9),
                                new Cell(true, false, false, false, 13, 10),
                                new Cell(false, true, true, false, 13, 11),
                                new Cell(true, true, false, true, 13, 12),
                                new Cell(true, false, true, false, 13, 13),
                                new Cell(false, true, false, false, 13, 14),
                                new Cell(true, true, false, false, 13, 15),
                                new Cell(true, true, false, true, 13, 16),
                                new Cell(true, true, false, false, 13, 17),
                                new Cell(true, true, false, false, 13, 18),
                                new Cell(true, false, false, true, 13, 19),
                                new Cell(false, true, false, true, 13, 20),
                                new Cell(true, true, false, false, 13, 21),
                                new Cell(true, true, false, false, 13, 22),
                                new Cell(true, true, false, false, 13, 23),
                                new Cell(true, false, true, false, 13, 24)
                        },
                        {
                                new Cell(false, true, false, true, 14, 0),
                                new Cell(true, true, false, false, 14, 1),
                                new Cell(true, true, false, false, 14, 2),
                                new Cell(true, true, true, false, 14, 3),
                                new Cell(true, true, true, false, 14, 4),
                                new Cell(true, true, false, false, 14, 5),
                                new Cell(true, true, false, false, 14, 6),
                                new Cell(true, false, false, true, 14, 7),
                                new Cell(false, true, true, false, 14, 8),
                                new Cell(true, true, false, false, 14, 9),
                                new Cell(true, true, false, false, 14, 10),
                                new Cell(true, true, false, false, 14, 11),
                                new Cell(true, true, true, false, 14, 12),
                                new Cell(true, true, false, false, 14, 13),
                                new Cell(true, true, false, false, 14, 14),
                                new Cell(true, true, false, false, 14, 15),
                                new Cell(true, false, true, true, 14, 16),
                                new Cell(false, true, false, false, 14, 17),
                                new Cell(true, true, false, false, 14, 18),
                                new Cell(true, true, true, false, 14, 19),
                                new Cell(true, true, true, false, 14, 20),
                                new Cell(true, true, false, false, 14, 21),
                                new Cell(true, true, false, false, 14, 22),
                                new Cell(true, true, false, false, 14, 23),
                                new Cell(true, false, false, true, 14, 24)
                        },
                        {
                                new Cell(false, true, true, false, 15, 0),
                                new Cell(true, true, false, false, 15, 1),
                                new Cell(true, true, false, false, 15, 2),
                                new Cell(true, true, false, false, 15, 3),
                                new Cell(true, true, false, true, 15, 4),
                                new Cell(true, true, false, false, 15, 5),
                                new Cell(true, true, false, false, 15, 6),
                                new Cell(true, false, true, false, 15, 7),
                                new Cell(false, true, false, false, 15, 8),
                                new Cell(true, true, false, false, 15, 9),
                                new Cell(true, true, false, false, 15, 10),
                                new Cell(true, true, false, false, 15, 11),
                                new Cell(true, true, false, true, 15, 12),
                                new Cell(true, true, false, false, 15, 13),
                                new Cell(true, true, false, false, 15, 14),
                                new Cell(true, true, false, false, 15, 15),
                                new Cell(true, false, true, false, 15, 16),
                                new Cell(false, true, false, false, 15, 17),
                                new Cell(true, true, false, false, 15, 18),
                                new Cell(true, true, false, false, 15, 19),
                                new Cell(true, true, false, false, 15, 20),
                                new Cell(true, true, false, true, 15, 21),
                                new Cell(true, true, false, false, 15, 22),
                                new Cell(true, true, false, false, 15, 23),
                                new Cell(true, false, true, false, 15, 24)
                        },
                        {
                                new Cell(false, true, false, true, 16, 0),
                                new Cell(true, true, false, false, 16, 1),
                                new Cell(true, true, false, false, 16, 2),
                                new Cell(true, false, false, false, 16, 3),
                                new Cell(false, false, true, true, 16, 4),
                                new Cell(false, true, false, true, 16, 5),
                                new Cell(true, false, false, true, 16, 6),
                                new Cell(false, false, false, true, 16, 7),
                                new Cell(false, true, false, true, 16, 8),
                                new Cell(true, true, false, false, 16, 9),
                                new Cell(true, true, false, false, 16, 10),
                                new Cell(true, true, false, false, 16, 11),
                                new Cell(true, true, true, false, 16, 12),
                                new Cell(true, true, false, false, 16, 13),
                                new Cell(true, true, false, false, 16, 14),
                                new Cell(true, true, false, false, 16, 15),
                                new Cell(true, false, false, true, 16, 16),
                                new Cell(false, true, false, false, 16, 17),
                                new Cell(true, true, false, false, 16, 18),
                                new Cell(true, true, false, false, 16, 19),
                                new Cell(true, true, false, false, 16, 20),
                                new Cell(true, true, true, false, 16, 21),
                                new Cell(true, true, false, false, 16, 22),
                                new Cell(true, true, false, false, 16, 23),
                                new Cell(true, false, false, true, 16, 24)
                        },
                        {
                                new Cell(false, true, true, true, 17, 0),
                                new Cell(true, true, false, false, 17, 1),
                                new Cell(true, true, false, false, 17, 2),
                                new Cell(true, true, false, false, 17, 3),
                                new Cell(true, true, true, false, 17, 4),
                                new Cell(true, false, true, false, 17, 5),
                                new Cell(false, true, true, false, 17, 6),
                                new Cell(true, false, true, true, 17, 7),
                                new Cell(false, true, true, false, 17, 8),
                                new Cell(true, true, false, false, 17, 9),
                                new Cell(true, true, false, false, 17, 10),
                                new Cell(true, true, false, false, 17, 11),
                                new Cell(true, true, false, false, 17, 12),
                                new Cell(true, false, false, true, 17, 13),
                                new Cell(false, true, false, true, 17, 14),
                                new Cell(true, false, false, true, 17, 15),
                                new Cell(false, true, true, false, 17, 16),
                                new Cell(true, true, false, false, 17, 17),
                                new Cell(true, false, false, true, 17, 18),
                                new Cell(false, true, false, true, 17, 19),
                                new Cell(true, true, false, false, 17, 20),
                                new Cell(true, true, false, false, 17, 21),
                                new Cell(true, true, false, false, 17, 22),
                                new Cell(true, false, false, true, 17, 23),
                                new Cell(false, false, true, true, 17, 24)
                        },
                        {
                                new Cell(false, true, true, false, 18, 0),
                                new Cell(true, true, false, false, 18, 1),
                                new Cell(true, true, false, false, 18, 2),
                                new Cell(true, true, false, false, 18, 3),
                                new Cell(true, true, false, false, 18, 4),
                                new Cell(true, true, false, false, 18, 5),
                                new Cell(true, false, false, true, 18, 6),
                                new Cell(false, true, true, false, 18, 7),
                                new Cell(true, true, false, false, 18, 8),
                                new Cell(true, true, false, false, 18, 9),
                                new Cell(true, true, false, false, 18, 10),
                                new Cell(true, true, false, false, 18, 11),
                                new Cell(true, false, false, true, 18, 12),
                                new Cell(false, false, true, true, 18, 13),
                                new Cell(false, false, true, true, 18, 14),
                                new Cell(false, true, true, false, 18, 15),
                                new Cell(true, true, false, false, 18, 16),
                                new Cell(true, true, false, false, 18, 17),
                                new Cell(true, false, true, false, 18, 18),
                                new Cell(false, true, true, false, 18, 19),
                                new Cell(true, true, false, false, 18, 20),
                                new Cell(true, true, false, false, 18, 21),
                                new Cell(true, false, false, true, 18, 22),
                                new Cell(false, false, true, true, 18, 23),
                                new Cell(false, false, true, true, 18, 24)
                        },
                        {
                                new Cell(false, true, false, true, 19, 0),
                                new Cell(true, true, false, false, 19, 1),
                                new Cell(true, true, false, false, 19, 2),
                                new Cell(true, true, false, false, 19, 3),
                                new Cell(true, true, false, true, 19, 4),
                                new Cell(true, true, false, false, 19, 5),
                                new Cell(true, true, true, true, 19, 6),
                                new Cell(true, true, false, false, 19, 7),
                                new Cell(true, true, false, false, 19, 8),
                                new Cell(true, true, false, false, 19, 9),
                                new Cell(true, true, false, false, 19, 10),
                                new Cell(true, false, false, true, 19, 11),
                                new Cell(false, true, true, false, 19, 12),
                                new Cell(true, false, true, false, 19, 13),
                                new Cell(false, true, true, false, 19, 14),
                                new Cell(true, true, false, false, 19, 15),
                                new Cell(true, true, false, false, 19, 16),
                                new Cell(true, false, false, true, 19, 17),
                                new Cell(false, true, false, true, 19, 18),
                                new Cell(true, true, false, false, 19, 19),
                                new Cell(true, true, false, false, 19, 20),
                                new Cell(true, true, false, false, 19, 21),
                                new Cell(true, false, true, false, 19, 22),
                                new Cell(false, false, true, true, 19, 23),
                                new Cell(false, false, true, true, 19, 24)
                        },
                        {
                                new Cell(false, true, true, false, 20, 0),
                                new Cell(true, true, false, false, 20, 1),
                                new Cell(true, true, false, false, 20, 2),
                                new Cell(true, false, false, false, 20, 3),
                                new Cell(false, true, true, true, 20, 4),
                                new Cell(true, true, false, false, 20, 5),
                                new Cell(true, true, true, true, 20, 6),
                                new Cell(true, true, false, false, 20, 7),
                                new Cell(true, true, false, false, 20, 8),
                                new Cell(true, true, false, true, 20, 9),
                                new Cell(true, true, false, false, 20, 10),
                                new Cell(true, true, true, false, 20, 11),
                                new Cell(true, true, false, false, 20, 12),
                                new Cell(true, true, false, false, 20, 13),
                                new Cell(true, true, false, true, 20, 14),
                                new Cell(true, true, false, false, 20, 15),
                                new Cell(true, false, false, false, 20, 16),
                                new Cell(false, false, true, true, 20, 17),
                                new Cell(false, false, true, true, 20, 18),
                                new Cell(false, true, false, true, 20, 19),
                                new Cell(true, true, false, false, 20, 20),
                                new Cell(true, true, false, false, 20, 21),
                                new Cell(true, true, false, false, 20, 22),
                                new Cell(true, false, true, false, 20, 23),
                                new Cell(false, false, true, true, 20, 24)
                        },
                        {
                                new Cell(false, true, false, true, 21, 0),
                                new Cell(true, true, false, false, 21, 1),
                                new Cell(true, true, false, false, 21, 2),
                                new Cell(true, true, false, false, 21, 3),
                                new Cell(true, true, true, false, 21, 4),
                                new Cell(true, true, false, false, 21, 5),
                                new Cell(true, false, true, false, 21, 6),
                                new Cell(false, true, false, true, 21, 7),
                                new Cell(true, false, false, true, 21, 8),
                                new Cell(false, true, true, false, 21, 9),
                                new Cell(true, true, false, false, 21, 10),
                                new Cell(true, true, false, false, 21, 11),
                                new Cell(true, true, false, false, 21, 12),
                                new Cell(true, false, false, true, 21, 13),
                                new Cell(false, true, true, false, 21, 14),
                                new Cell(true, true, false, false, 21, 15),
                                new Cell(true, false, false, true, 21, 16),
                                new Cell(false, true, true, false, 21, 17),
                                new Cell(true, false, true, false, 21, 18),
                                new Cell(false, true, true, true, 21, 19),
                                new Cell(true, true, false, false, 21, 20),
                                new Cell(true, true, false, false, 21, 21),
                                new Cell(true, true, false, false, 21, 22),
                                new Cell(true, true, false, false, 21, 23),
                                new Cell(true, false, true, false, 21, 24)
                        },
                        {
                                new Cell(false, true, true, false, 22, 0),
                                new Cell(true, true, false, false, 22, 1),
                                new Cell(true, true, false, false, 22, 2),
                                new Cell(true, true, false, false, 22, 3),
                                new Cell(true, true, false, false, 22, 4),
                                new Cell(true, true, false, false, 22, 5),
                                new Cell(true, true, false, false, 22, 6),
                                new Cell(true, false, true, false, 22, 7),
                                new Cell(false, true, true, true, 22, 8),
                                new Cell(true, true, false, false, 22, 9),
                                new Cell(true, true, false, false, 22, 10),
                                new Cell(true, true, false, false, 22, 11),
                                new Cell(true, false, false, true, 22, 12),
                                new Cell(false, true, true, false, 22, 13),
                                new Cell(true, true, false, false, 22, 14),
                                new Cell(true, false, false, true, 22, 15),
                                new Cell(false, true, true, false, 22, 16),
                                new Cell(true, true, false, false, 22, 17),
                                new Cell(true, true, false, true, 22, 18),
                                new Cell(true, false, true, false, 22, 19),
                                new Cell(false, true, false, true, 22, 20),
                                new Cell(true, true, false, true, 22, 21),
                                new Cell(true, false, false, false, 22, 22),
                                new Cell(false, true, false, true, 22, 23),
                                new Cell(true, false, false, true, 22, 24)
                        },
                        {
                                new Cell(false, true, false, true, 23, 0),
                                new Cell(true, true, false, false, 23, 1),
                                new Cell(true, true, false, false, 23, 2),
                                new Cell(true, true, false, false, 23, 3),
                                new Cell(true, true, false, false, 23, 4),
                                new Cell(true, true, false, false, 23, 5),
                                new Cell(true, true, false, false, 23, 6),
                                new Cell(true, true, false, false, 23, 7),
                                new Cell(true, false, true, false, 23, 8),
                                new Cell(false, true, false, true, 23, 9),
                                new Cell(true, true, false, false, 23, 10),
                                new Cell(true, false, false, true, 23, 11),
                                new Cell(false, true, true, false, 23, 12),
                                new Cell(true, true, false, false, 23, 13),
                                new Cell(true, false, false, true, 23, 14),
                                new Cell(false, true, true, false, 23, 15),
                                new Cell(true, true, false, false, 23, 16),
                                new Cell(true, false, false, true, 23, 17),
                                new Cell(false, true, true, false, 23, 18),
                                new Cell(true, true, false, false, 23, 19),
                                new Cell(true, false, true, false, 23, 20),
                                new Cell(false, true, true, false, 23, 21),
                                new Cell(true, true, false, false, 23, 22),
                                new Cell(true, false, true, false, 23, 23),
                                new Cell(false, false, true, true, 23, 24)
                        },
                        {
                                new Cell(false, true, true, false, 24, 0),
                                new Cell(true, true, false, false, 24, 1),
                                new Cell(true, true, false, false, 24, 2),
                                new Cell(true, true, false, false, 24, 3),
                                new Cell(true, true, false, false, 24, 4),
                                new Cell(true, true, false, false, 24, 5),
                                new Cell(true, true, false, false, 24, 6),
                                new Cell(true, true, false, false, 24, 7),
                                new Cell(true, true, false, false, 24, 8),
                                new Cell(true, false, true, false, 24, 9),
                                new Cell(false, false, false, false, 24, 10),
                                new Cell(false, true, true, false, 24, 11),
                                new Cell(true, true, false, false, 24, 12),
                                new Cell(true, true, false, false, 24, 13),
                                new Cell(true, true, true, false, 24, 14),
                                new Cell(true, true, false, false, 24, 15),
                                new Cell(true, true, false, false, 24, 16),
                                new Cell(true, true, true, false, 24, 17),
                                new Cell(true, true, false, false, 24, 18),
                                new Cell(true, true, false, false, 24, 19),
                                new Cell(true, true, false, false, 24, 20),
                                new Cell(true, true, false, false, 24, 21),
                                new Cell(true, true, false, false, 24, 22),
                                new Cell(true, true, false, false, 24, 23),
                                new Cell(true, false, true, false, 24, 24)
                        }
                };
        }

        @Override
        public void parseCell(JsonObject cell, int line, int column) {
                if (cell.has("occupant")) {
                        Long occupantId = cell.get("occupant").getAsJsonObject().get("id").getAsLong();
                        getIaById(occupantId).setCell(labyrinth[line][column]);
                }
        }

        @Override
        public void initNbLines(int nb) {

        }

        @Override
        public void initNbCellsInLine(int lineNumber, int nb) {

        }
}
